/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import canvasframe.CanvasPanel;
import java.awt.Graphics;
/**
 *
 * @author BS117017
 */
public class paintAppTest extends javax.swing.JFrame {

    /**
     * Creates new form paintAppTest
     */
    public paintAppTest() {
          canvas =new CanvasPanel();
          Graphics bg=canvas.getBG();
          pen=new Pen();
          Rectangle tip=new Rectangle(bg);
          tip.setColor(255,0 , 0);
          pen.setTip(tip);
          
          
          initComponents();
          
          getContentPane().add(canvas, java.awt.BorderLayout.CENTER);
          canvas.getComponent().addMouseMotionListener(pen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipBtnGroup = new javax.swing.ButtonGroup();
        tipPanel = new javax.swing.JPanel();
        rectTipBtn = new javax.swing.JToggleButton();
        ovalTipBtn = new javax.swing.JToggleButton();
        dotTipBtn = new javax.swing.JToggleButton();
        controlPanel = new javax.swing.JPanel();
        colorPanel = new javax.swing.JPanel();
        colorSamplePanel = new javax.swing.JPanel();
        rSliderPanel = new javax.swing.JPanel();
        rLabel = new javax.swing.JLabel();
        rSlider = new javax.swing.JSlider();
        rValueLabel = new javax.swing.JLabel();
        gSliderPanel = new javax.swing.JPanel();
        gLabel = new javax.swing.JLabel();
        gSlider = new javax.swing.JSlider();
        gValueLabel = new javax.swing.JLabel();
        bSliderPanel = new javax.swing.JPanel();
        bLabel = new javax.swing.JLabel();
        bSlider = new javax.swing.JSlider();
        bValueLabel = new javax.swing.JLabel();
        sizePanel = new javax.swing.JPanel();
        wSliderPanel = new javax.swing.JPanel();
        wLabel = new javax.swing.JLabel();
        wSlider = new javax.swing.JSlider();
        wValueLabel = new javax.swing.JLabel();
        hSliderPanel = new javax.swing.JPanel();
        hLabel = new javax.swing.JLabel();
        hSlider = new javax.swing.JSlider();
        hValueLabel = new javax.swing.JLabel();
        nullPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveItem = new javax.swing.JMenuItem();
        quitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tipPanel.setPreferredSize(new java.awt.Dimension(50, 300));
        tipPanel.setLayout(new javax.swing.BoxLayout(tipPanel, javax.swing.BoxLayout.Y_AXIS));

        tipBtnGroup.add(rectTipBtn);
        rectTipBtn.setSelected(true);
        rectTipBtn.setText("■");
        rectTipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectTipBtnActionPerformed(evt);
            }
        });
        tipPanel.add(rectTipBtn);

        tipBtnGroup.add(ovalTipBtn);
        ovalTipBtn.setText("●");
        ovalTipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovalTipBtnActionPerformed(evt);
            }
        });
        tipPanel.add(ovalTipBtn);

        tipBtnGroup.add(dotTipBtn);
        dotTipBtn.setText("・");
        dotTipBtn.setMaximumSize(new java.awt.Dimension(45, 21));
        dotTipBtn.setMinimumSize(new java.awt.Dimension(45, 21));
        dotTipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotTipBtnActionPerformed(evt);
            }
        });
        tipPanel.add(dotTipBtn);

        getContentPane().add(tipPanel, java.awt.BorderLayout.WEST);

        controlPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        controlPanel.setPreferredSize(new java.awt.Dimension(200, 300));
        controlPanel.setLayout(new javax.swing.BoxLayout(controlPanel, javax.swing.BoxLayout.Y_AXIS));

        colorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));
        colorPanel.setPreferredSize(new java.awt.Dimension(96, 150));
        colorPanel.setLayout(new javax.swing.BoxLayout(colorPanel, javax.swing.BoxLayout.Y_AXIS));

        colorSamplePanel.setBackground(new java.awt.Color(255, 0, 0));
        colorSamplePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        colorSamplePanel.setPreferredSize(new java.awt.Dimension(184, 50));

        javax.swing.GroupLayout colorSamplePanelLayout = new javax.swing.GroupLayout(colorSamplePanel);
        colorSamplePanel.setLayout(colorSamplePanelLayout);
        colorSamplePanelLayout.setHorizontalGroup(
            colorSamplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        colorSamplePanelLayout.setVerticalGroup(
            colorSamplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        colorPanel.add(colorSamplePanel);

        rSliderPanel.setLayout(new javax.swing.BoxLayout(rSliderPanel, javax.swing.BoxLayout.LINE_AXIS));

        rLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rLabel.setText("r");
        rLabel.setPreferredSize(new java.awt.Dimension(20, 16));
        rSliderPanel.add(rLabel);

        rSlider.setMaximum(255);
        rSlider.setValue(255);
        rSliderPanel.add(rSlider);

        rValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rValueLabel.setText("255");
        rValueLabel.setPreferredSize(new java.awt.Dimension(30, 16));
        rSliderPanel.add(rValueLabel);

        colorPanel.add(rSliderPanel);

        gSliderPanel.setLayout(new javax.swing.BoxLayout(gSliderPanel, javax.swing.BoxLayout.LINE_AXIS));

        gLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gLabel.setText("g");
        gLabel.setPreferredSize(new java.awt.Dimension(20, 16));
        gSliderPanel.add(gLabel);

        gSlider.setMaximum(255);
        gSlider.setPaintLabels(true);
        gSlider.setValue(0);
        gSliderPanel.add(gSlider);

        gValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gValueLabel.setText("0");
        gValueLabel.setPreferredSize(new java.awt.Dimension(30, 16));
        gSliderPanel.add(gValueLabel);

        colorPanel.add(gSliderPanel);

        bSliderPanel.setLayout(new javax.swing.BoxLayout(bSliderPanel, javax.swing.BoxLayout.LINE_AXIS));

        bLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bLabel.setText("b");
        bLabel.setPreferredSize(new java.awt.Dimension(20, 16));
        bSliderPanel.add(bLabel);

        bSlider.setMaximum(255);
        bSlider.setPaintLabels(true);
        bSlider.setValue(0);
        bSliderPanel.add(bSlider);

        bValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bValueLabel.setText("0");
        bValueLabel.setPreferredSize(new java.awt.Dimension(30, 16));
        bSliderPanel.add(bValueLabel);

        colorPanel.add(bSliderPanel);

        controlPanel.add(colorPanel);

        sizePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Size"));
        sizePanel.setPreferredSize(new java.awt.Dimension(96, 100));
        sizePanel.setLayout(new java.awt.GridLayout(2, 1));

        wSliderPanel.setLayout(new javax.swing.BoxLayout(wSliderPanel, javax.swing.BoxLayout.LINE_AXIS));

        wLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wLabel.setText("w");
        wLabel.setPreferredSize(new java.awt.Dimension(20, 16));
        wSliderPanel.add(wLabel);

        wSlider.setPaintLabels(true);
        wSlider.setValue(10);
        wSliderPanel.add(wSlider);

        wValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wValueLabel.setText("10");
        wValueLabel.setPreferredSize(new java.awt.Dimension(30, 16));
        wSliderPanel.add(wValueLabel);

        sizePanel.add(wSliderPanel);

        hSliderPanel.setLayout(new javax.swing.BoxLayout(hSliderPanel, javax.swing.BoxLayout.LINE_AXIS));

        hLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hLabel.setText("h");
        hLabel.setPreferredSize(new java.awt.Dimension(20, 16));
        hSliderPanel.add(hLabel);

        hSlider.setPaintLabels(true);
        hSlider.setValue(10);
        hSliderPanel.add(hSlider);

        hValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hValueLabel.setText("10");
        hValueLabel.setPreferredSize(new java.awt.Dimension(30, 16));
        hSliderPanel.add(hValueLabel);

        sizePanel.add(hSliderPanel);

        controlPanel.add(sizePanel);

        javax.swing.GroupLayout nullPanelLayout = new javax.swing.GroupLayout(nullPanel);
        nullPanel.setLayout(nullPanelLayout);
        nullPanelLayout.setHorizontalGroup(
            nullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        nullPanelLayout.setVerticalGroup(
            nullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        controlPanel.add(nullPanel);

        getContentPane().add(controlPanel, java.awt.BorderLayout.EAST);

        fileMenu.setText("File");

        saveItem.setText("save");
        fileMenu.add(saveItem);

        quitItem.setText("quit");
        quitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitItemActionPerformed
        
    }//GEN-LAST:event_quitItemActionPerformed

    private void ovalTipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovalTipBtnActionPerformed
        Oval tip =new Oval(canvas.getBG());
        tip.setColor(0, 0, 255);
        pen.setTip(tip);
    }//GEN-LAST:event_ovalTipBtnActionPerformed

    private void rectTipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectTipBtnActionPerformed
       Rectangle tip =new Rectangle(canvas.getBG());
        tip.setColor(255, 0,0);
        pen.setTip(tip);
    }//GEN-LAST:event_rectTipBtnActionPerformed

    private void dotTipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotTipBtnActionPerformed
       Dot tip =new Dot(canvas.getBG());
        tip.setColor(0, 0, 255);
        pen.setTip(tip);
    }//GEN-LAST:event_dotTipBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paintAppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paintAppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paintAppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paintAppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paintAppTest().setVisible(true);
            }
        });
    }
    private Pen pen;
    private CanvasPanel canvas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bLabel;
    private javax.swing.JSlider bSlider;
    private javax.swing.JPanel bSliderPanel;
    private javax.swing.JLabel bValueLabel;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JPanel colorSamplePanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JToggleButton dotTipBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel gLabel;
    private javax.swing.JSlider gSlider;
    private javax.swing.JPanel gSliderPanel;
    private javax.swing.JLabel gValueLabel;
    private javax.swing.JLabel hLabel;
    private javax.swing.JSlider hSlider;
    private javax.swing.JPanel hSliderPanel;
    private javax.swing.JLabel hValueLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel nullPanel;
    private javax.swing.JToggleButton ovalTipBtn;
    private javax.swing.JMenuItem quitItem;
    private javax.swing.JLabel rLabel;
    private javax.swing.JSlider rSlider;
    private javax.swing.JPanel rSliderPanel;
    private javax.swing.JLabel rValueLabel;
    private javax.swing.JToggleButton rectTipBtn;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JPanel sizePanel;
    private javax.swing.ButtonGroup tipBtnGroup;
    private javax.swing.JPanel tipPanel;
    private javax.swing.JLabel wLabel;
    private javax.swing.JSlider wSlider;
    private javax.swing.JPanel wSliderPanel;
    private javax.swing.JLabel wValueLabel;
    // End of variables declaration//GEN-END:variables
}
